### ISSUE TITLE
question: how to highlight first option?

### ISSUE THREAD

**Issue by diocletiann** [ggandor/flit.nvim#49]
Thanks for the amazing plugin, I finally use f because of it! 

One thing I would like to improve, currently the first hit in a line doesn't get highlighted which is a bit confusing, and requires pressing esc to move the cursor there. Would it be possible to highlight it using the same char so I can just press the same char again? I think it would be very intuitive, and wouldn't require changing the logic for the other jump chars.

**Comment by diocletiann** [comment]
update: the first hit is now auto selected, maybe LazyVim tweaked something.

**Comment by ggandor** [comment]
This is a bug fixed by https://github.com/ggandor/leap.nvim/commit/f1f19fc268b406b00b50091f51f16d9634fbe449 on nightly. The cursor is moved to the first match automatically (no need for `esc`), but due to an nvim bug, it was not redrawn on the screen (if you'd have pressed e.g. `l` afterwards, you could have seen it moving to the column next to the match). 

https://github.com/ggandor/leap.nvim/issues/70
